import React from 'react';
import { Geist, Geist_Mono } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function adminPage({ children }) {
    return (
      <html lang="en">

      </html>
    );
  }
  