import React from 'react';
import SNavbar from '@/Components/SNavbar/SNavbar';
import ComplaintForm from '@/Components/StudentComps/complaint';
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function StudentLayout({ children }) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <SNavbar />
            <ComplaintForm />
          {children}
            
        </body>
      </html>
    );
  }
  